// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Ui from "./Ui.bs.js";
import * as React from "react";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as ReactNative from "react-native";
import * as NewAppScreen from "react-native/Libraries/NewAppScreen";

var styles = ReactNative.StyleSheet.create({
      scrollView: {
        backgroundColor: NewAppScreen.Colors.lighter
      },
      engine: {
        position: "absolute",
        right: 0
      },
      body: {
        backgroundColor: NewAppScreen.Colors.white
      },
      sectionContainer: {
        marginTop: 32,
        paddingHorizontal: 24
      },
      sectionTitle: {
        color: NewAppScreen.Colors.black,
        fontSize: 24,
        fontWeight: "600"
      },
      sectionDescription: {
        color: NewAppScreen.Colors.dark,
        fontSize: 18,
        fontWeight: "400",
        marginTop: 8
      },
      highlight: {
        fontWeight: "700"
      },
      footer: {
        color: NewAppScreen.Colors.dark,
        fontSize: 12,
        fontWeight: "600",
        textAlign: "right",
        padding: 4,
        paddingRight: 12
      }
    });

function App$app(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement(ReactNative.StatusBar, {
                  barStyle: "dark-content"
                }), React.createElement(ReactNative.SafeAreaView, {
                  children: React.createElement(ReactNative.ScrollView, {
                        contentInsetAdjustmentBehavior: "automatic",
                        style: styles.scrollView,
                        children: null
                      }, Belt_Option.isNone(global.hermesInternal) ? null : React.createElement(ReactNative.View, {
                              style: styles.engine,
                              children: React.createElement(ReactNative.Text, {
                                    style: styles.footer,
                                    children: "Engine: Hermes"
                                  })
                            }), React.createElement(ReactNative.View, {
                            style: styles.body,
                            children: React.createElement(Ui.v, { })
                          }))
                }));
}

var app = App$app;

export {
  styles ,
  app ,
  
}
/* styles Not a pure module */
