// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Model from "./Model.bs.js";
import * as React from "react";
import * as Pervasives from "bs-platform/lib/es6/pervasives.js";
import * as ReactNative from "react-native";

function Ui$v(Props) {
  var match = React.useReducer(Model.reducer, {
        durationInput: -1.0,
        timerStartTime: -1.0
      });
  var dispatch = match[1];
  var state = match[0];
  return React.createElement(ReactNative.View, {
              children: null
            }, React.createElement(ReactNative.Text, {
                  children: Pervasives.string_of_float(state.durationInput)
                }), React.createElement(ReactNative.TextInput, {
                  onChange: (function (changeEvent) {
                      return Curry._1(dispatch, /* SetDuration */[changeEvent.nativeEvent.text]);
                    }),
                  placeholder: "time in ms"
                }), React.createElement(ReactNative.TouchableOpacity, {
                  onPress: (function (param) {
                      return Curry._1(dispatch, /* SetDuration */[Pervasives.string_of_float(state.durationInput - 1.0)]);
                    }),
                  children: React.createElement(ReactNative.Text, {
                        children: "Start"
                      })
                }));
}

var v = Ui$v;

export {
  v ,
  
}
/* react Not a pure module */
