// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Model from "./Model.bs.js";
import * as React from "react";
import * as Js_math from "bs-platform/lib/es6/js_math.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as ReactNative from "react-native";

function presentDuration(d) {
  var minutes = Js_math.floor(d / 60000.0);
  var seconds = Js_math.floor(d / 1000.0) % 60;
  var millis = Js_math.floor(d) % 1000;
  return minutes.toString() + (":" + (seconds.toString() + ("." + millis.toString())));
}

function durationInputToTime(prim) {
  return Number(prim);
}

function Ui$TimeLeft$v(Props) {
  var state = Props.state;
  var t = Belt_Option.getWithDefault(state.timeLeft, Number(state.durationInput));
  return React.createElement(ReactNative.Text, {
              children: presentDuration(t)
            });
}

var TimeLeft = {
  v: Ui$TimeLeft$v
};

function Ui$v(Props) {
  var match = React.useReducer(Model.reducer, Model.initState);
  var dispatch = match[1];
  return React.createElement(ReactNative.View, {
              children: null
            }, React.createElement(Ui$TimeLeft$v, {
                  state: match[0]
                }), React.createElement(ReactNative.TextInput, {
                  onChange: (function (changeEvent) {
                      return Curry._1(dispatch, /* SetDuration */Block.__(1, [changeEvent.nativeEvent.text]));
                    }),
                  placeholder: "time in ms"
                }), React.createElement(ReactNative.TouchableOpacity, {
                  onPress: (function (param) {
                      return Curry._1(dispatch, /* Start */Block.__(0, [(function (param) {
                                        Curry._1(dispatch, param);
                                        
                                      })]));
                    }),
                  children: React.createElement(ReactNative.Text, {
                        children: "Start"
                      })
                }), React.createElement(ReactNative.TouchableOpacity, {
                  onPress: (function (param) {
                      return Curry._1(dispatch, /* Stop */1);
                    }),
                  children: React.createElement(ReactNative.Text, {
                        children: "Stop"
                      })
                }));
}

var v = Ui$v;

export {
  presentDuration ,
  durationInputToTime ,
  TimeLeft ,
  v ,
  
}
/* react Not a pure module */
