// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Model from "./Model.bs.js";
import * as React from "react";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as ReactNative from "react-native";

function presentDuration(d) {
  return d.toString();
}

function Ui$Duration$v(Props) {
  var state = Props.state;
  var t = Belt_Option.getWithDefault(state.timeLeft, state.durationInput);
  return React.createElement(ReactNative.Text, {
              children: t.toString()
            });
}

var Duration = {
  v: Ui$Duration$v
};

function Ui$v(Props) {
  var r = function (a, b) {
    return Model.withCoeffect(Model.reducer, a, b)[0];
  };
  var match = React.useReducer(r, Model.initState);
  var dispatch = match[1];
  return React.createElement(ReactNative.View, {
              children: null
            }, React.createElement(Ui$Duration$v, {
                  state: match[0]
                }), React.createElement(ReactNative.TextInput, {
                  onChange: (function (changeEvent) {
                      return Curry._1(dispatch, /* SetDuration */Block.__(1, [changeEvent.nativeEvent.text]));
                    }),
                  placeholder: "time in ms"
                }), React.createElement(ReactNative.TouchableOpacity, {
                  onPress: (function (param) {
                      return Curry._1(dispatch, /* Start */Block.__(0, [(function (param) {
                                        Curry._1(dispatch, param);
                                        
                                      })]));
                    }),
                  children: React.createElement(ReactNative.Text, {
                        children: "Start"
                      })
                }), React.createElement(ReactNative.TouchableOpacity, {
                  onPress: (function (param) {
                      return Curry._1(dispatch, /* Stop */1);
                    }),
                  children: React.createElement(ReactNative.Text, {
                        children: "Stop"
                      })
                }));
}

var v = Ui$v;

export {
  presentDuration ,
  Duration ,
  v ,
  
}
/* react Not a pure module */
